//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShopApp.Model
{
    using System;
    using System.Collections.Generic;
    using ShoeShopApp.ViewModel;
    
    public partial class LoaiNV:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiNV()
        {
            this.NhanViens = new HashSet<NhanVien>();
        }

        private int _MaLoaiNV;
        public int MaLoaiNV { get=> _MaLoaiNV; set { _MaLoaiNV = value;OnPropertyChanged(); } }
        private string _TenLoaiNV;
        public string TenLoaiNV { get=> _TenLoaiNV; set { _TenLoaiNV = value;OnPropertyChanged(); } }
        private Nullable<decimal> _TienThuong;
        public Nullable<decimal> TienThuong { get=> _TienThuong; set { _TienThuong = value;OnPropertyChanged(); } }

        private bool _isDeleted;
        public bool isDeleted { get=> _isDeleted; set { _isDeleted = value;OnPropertyChanged(); } }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
