//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShopApp.Model
{
    using System;
    using System.Collections.Generic;
    using ShoeShopApp.Model;
    using ShoeShopApp.ViewModel;

    public partial class LoaiSP:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSP()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
        private int _MaLoaiSP;
        public int MaLoaiSP { get=>_MaLoaiSP; set { _MaLoaiSP = value;OnPropertyChanged(); } }

        private string _TenLoaiSP;
        public string TenLoaiSP { get =>_TenLoaiSP; set { _TenLoaiSP = value;OnPropertyChanged(); } }

        private string _NoiSanXuat;
        public string NoiSanXuat { get=>_NoiSanXuat; set { _NoiSanXuat = value;OnPropertyChanged(); } }

        private int _MaNCC;
        public int MaNCC { get=>_MaNCC; set { _MaNCC = value;OnPropertyChanged(); } }

        private bool _isDeleted;
        public bool isDeleted { get=>_isDeleted; set { _isDeleted = value;OnPropertyChanged(); } }

        private NhaCungCap _NhaCungCap;
        public virtual NhaCungCap NhaCungCap { get=> _NhaCungCap; set { _NhaCungCap = value;OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
