//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShopApp.Model
{
    using ShoeShopApp.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiSP:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiSP()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
        int _MaLoaiSP;
        public int MaLoaiSP { get => _MaLoaiSP; set { _MaLoaiSP = value; OnPropertyChanged(); } }
        
        string _TenLoaiSP;
        public string TenLoaiSP { get => _TenLoaiSP; set { _TenLoaiSP = value; OnPropertyChanged(); } }

        string _NoiSanXuat;
        public string NoiSanXuat { get => _NoiSanXuat; set { _NoiSanXuat = value; OnPropertyChanged(); } }

        int _MaNCC;
        public int MaNCC { get => _MaNCC; set { _MaNCC = value; OnPropertyChanged(); } }

        bool _isDeleted;
        public bool isDeleted { get => _isDeleted; set { _isDeleted = value; OnPropertyChanged(); } }
        
    
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
