//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeShopApp.Model
{
    using ShoeShopApp.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham:BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiaTietHoaDons = new HashSet<ChiaTietHoaDon>();
        }
    
        int _MaSP;
        public int MaSP { get => _MaSP; set { _MaSP = value; OnPropertyChanged(); }}

        string _TenSP;
        public string TenSP { get => _TenSP; set { _TenSP = value; OnPropertyChanged(); } }

        int _MaLoaiSP;
        public int MaLoaiSP { get => _MaLoaiSP; set { _MaLoaiSP = value; OnPropertyChanged(); } }

        decimal _Gia;
        public decimal Gia { get => _Gia; set { _Gia = value; OnPropertyChanged(); } }

        string _Mau;
        public string Mau { get => _Mau; set { _Mau = value; OnPropertyChanged(); } }

        Nullable<int> _SoLuong;
        public Nullable<int> SoLuong { get => _SoLuong; set { _SoLuong = value; OnPropertyChanged(); } }

        string _Anh;
        public string Anh { get => _Anh; set { _Anh = value; OnPropertyChanged(); } }

        bool _isDeleted;
        public bool isDeleted { get => _isDeleted; set { _isDeleted = value; OnPropertyChanged(); } }
            
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiaTietHoaDon> ChiaTietHoaDons { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
